spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1/companies/**
        - id: discovery-service
          uri: http://discovery-service:8761
          predicates:
            - Path=/eureka/**
        - id: config-service
          uri: lb://CONFIG-SERVICE
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: gateway-service
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      zone: docker

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
